Repository mohammadaminrez/SongBuddy, pull requests merged in 2025-09, with the labels that each got.

#54 Profile: time-range toggle + modern loading UX
  lib/screens/profile_screen.dart
Labels: Frontend

#55 34 social connections home page
  lib/screens/home_feed_screen.dart
Labels: Frontend

#58 Implement voice search and fix Home search bar behavior
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/screens/home_feed_screen.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: Frontend

#59 39 epic profile page redesign spotify
  lib/constants/app_colors.dart
  lib/constants/app_text_styles.dart
  lib/screens/home_feed_screen.dart
  lib/screens/profile_screen.dart
Labels: Frontend, spotify

#69 68 redesign and refine the homepage layout for a cleaner more consistent experience
  lib/screens/home_feed_screen.dart
  lib/screens/search_feed_screen.dart
  lib/screens/user_profile_screen.dart
Labels: Frontend, spotify, ui, ux, refactor

#77 feat : activate share burron for this page
  lib/screens/home_feed_screen.dart
Labels: enhancement, dart, Frontend, ui, ux

#79 refactor : add follow button and change the share and like button pos…
  lib/screens/search_feed_screen.dart
Labels: Frontend, ui, ux, refactor

#81 fix : fixing bug related to onboarding screens
  lib/screens/on_boarding/onboarding_page.dart
Labels: bug, Frontend, ui, ux

#93 90 make post
  lib/models/AppUser.dart
  lib/models/Post.dart
  lib/models/ProfileData.dart
  lib/screens/create_post_screen.dart
  lib/screens/profile_screen.dart
  lib/screens/search_feed_screen.dart
  lib/screens/user_profile_screen.dart
  lib/services/backend_service.dart
  lib/services/spotify_deep_link_service.dart
  lib/widgets/music_post_card.dart
  lib/widgets/swipeable_post_card.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement, dart, Frontend, Backend

#95 feat : adding the workflow of follow/following , show post of the fol…
  check_follow_status.bat
  create_feed_test_data.bat
  debug_backend_issue.md
  lib/models/ProfileData.dart
  lib/screens/home_feed_screen.dart
  lib/screens/profile_screen.dart
  lib/services/backend_service.dart
  test_feed_api.bat
  test_followers_api.bat
  test_followers_debug.bat
Labels: bug, enhancement, dart, Frontend, Backend, ui, ux

#101 100 improve code and fix bugs
  check_follow_status.bat
  create_feed_test_data.bat
  debug_backend_issue.md
  lib/main.dart
  lib/screens/create_post_screen.dart
  lib/screens/home_feed_screen.dart
  lib/screens/profile_screen.dart
  lib/screens/search_feed_screen.dart
  lib/screens/settings_screen.dart
  lib/widgets/create_post_sheet.dart
  lib/widgets/shimmer_post_card.dart
  test_feed_api.bat
  test_followers_api.bat
  test_followers_debug.bat
Labels: Frontend
